"""Add nullable poi_id to text_generation_jobs

Revision ID: 025e264e0e82
Revises: 43e0c43f7443
Create Date: 2025-07-31 06:55:31.101092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '025e264e0e82'
down_revision: Union[str, Sequence[str], None] = '43e0c43f7443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_generation_jobs', sa.Column('poi_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text_generation_jobs', 'poi_id')
    # ### end Alembic commands ###
