"""remove not null from poi_info_texts text

Revision ID: 43e0c43f7443
Revises: 6fc291ec58c3
Create Date: 2025-07-30 22:19:36.527750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e0c43f7443'
down_revision: Union[str, Sequence[str], None] = '6fc291ec58c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('poi_images_task_id_fkey'), 'poi_images', type_='foreignkey')
    op.create_foreign_key(None, 'poi_images', 'image_generation_jobs', ['task_id'], ['task_id'])
    op.alter_column('poi_info_texts', 'info_text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poi_info_texts', 'info_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'poi_images', type_='foreignkey')
    op.create_foreign_key(op.f('poi_images_task_id_fkey'), 'poi_images', 'image_generation_jobs', ['task_id'], ['task_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
