"""user role enum 4

Revision ID: 662a21498391
Revises: 38bbeff281d2
Create Date: 2025-07-29 16:45:43.314088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql 


# revision identifiers, used by Alembic.
revision: str = '662a21498391'
down_revision: Union[str, Sequence[str], None] = '38bbeff281d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy.dialects import postgresql
    user_role_enum = postgresql.ENUM('admin', 'user', 'premium', name='user_role')
    user_role_enum.create(op.get_bind())

    op.alter_column(
        'users',
        'role',
        existing_type=sa.VARCHAR(length=32),
        type_=user_role_enum,
        existing_nullable=False,
        postgresql_using="role::user_role"  # <-- This tells Postgres how to cast
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'user', 'premium', name='user_role'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    user_role_enum = postgresql.ENUM('admin', 'user', 'premium', name='user_role')
    user_role_enum.drop(op.get_bind())  # <-- Drop the enum type
    # ### end Alembic commands ###
