"""Add fastapi-users user and oauth tables

Revision ID: c9d14642c4bf
Revises: dff171b5ee39
Create Date: 2025-07-29 16:36:13.811410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9d14642c4bf'
down_revision: Union[str, Sequence[str], None] = 'dff171b5ee39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oauth_name', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.String(length=1024), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.String(length=1024), nullable=True),
    sa.Column('account_id', sa.String(length=320), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_accounts_account_id'), 'oauth_accounts', ['account_id'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_oauth_name'), 'oauth_accounts', ['oauth_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('planet_osm_ways_old_20250712181702')
    op.drop_table('planet_osm_ways_old_20250708200621')
    op.drop_table('osm2pgsql_properties')
    op.drop_index(op.f('planet_osm_new_roads_osm_id_idx'), table_name='planet_osm_new_roads')
    op.drop_index(op.f('planet_osm_new_roads_way_idx'), table_name='planet_osm_new_roads', postgresql_using='gist')
    op.drop_table('planet_osm_new_roads')
    op.alter_column('audio_generation_jobs', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('audio_generation_jobs', 'result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audio_prompt_templates', 'provider',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('audio_prompt_templates', 'model',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('audio_voices', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('generation_sources', 'model',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('image_aspects', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('image_generation_jobs', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('image_generation_jobs', 'result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('image_prompt_templates', 'provider',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('image_prompt_templates', 'model',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('osm_import_log', 'task_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('osm_import_log', 'regions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('osm_import_log', 'files',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('osm_import_log', 'error',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('osm_import_log', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('poi_audio', 'poi_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index(op.f('idx_poi_audio_task_id'), table_name='poi_audio')
    op.drop_index(op.f('unique_poi_audio_variant'), table_name='poi_audio')
    op.drop_constraint(op.f('poi_audio_generation_source_id_fkey'), 'poi_audio', type_='foreignkey')
    op.drop_column('poi_audio', 'generation_source_id')
    op.alter_column('poi_images', 'resolution',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='image_resolution'),
               nullable=False)
    op.alter_column('poi_images', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', name='enhancement_status'),
               nullable=False,
               existing_server_default=sa.text("'active'::enhancement_status"))
    op.alter_column('poi_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('poi_images', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('poi_images', 'style_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('poi_images', 'orphan',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_poi_images_task_id'), table_name='poi_images')
    op.drop_index(op.f('unique_poi_image_variant'), table_name='poi_images')
    op.drop_constraint(op.f('poi_images_generation_source_id_fkey'), 'poi_images', type_='foreignkey')
    op.drop_column('poi_images', 'generation_source_id')
    op.alter_column('poi_info_texts', 'info_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('poi_info_texts', 'text_length',
               existing_type=postgresql.ENUM('short', 'medium', 'long', 'very long', name='text_length'),
               nullable=False)
    op.alter_column('poi_info_texts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('poi_info_texts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('poi_info_texts_generation_source_id_fkey'), 'poi_info_texts', type_='foreignkey')
    op.drop_column('poi_info_texts', 'generation_source_id')
    op.drop_column('poi_info_texts', 'error_msg')
    op.drop_column('poi_info_texts', 'orphan')
    op.alter_column('text_generation_jobs', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('text_generation_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('text_generation_jobs', 'finished_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('text_generation_jobs', 'result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('text_generation_jobs', 'error_msg',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('text_prompt_templates', 'provider',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('text_prompt_templates', 'model',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('text_prompt_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('prompt_templates_provider_model_topic_id_style_id_version_key'), 'text_prompt_templates', type_='unique')
    op.create_unique_constraint('uq_prompt_template', 'text_prompt_templates', ['provider', 'model', 'topic_id', 'style_id', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_prompt_template', 'text_prompt_templates', type_='unique')
    op.create_unique_constraint(op.f('prompt_templates_provider_model_topic_id_style_id_version_key'), 'text_prompt_templates', ['provider', 'model', 'topic_id', 'style_id', 'version'], postgresql_nulls_not_distinct=False)
    op.alter_column('text_prompt_templates', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('text_prompt_templates', 'model',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('text_prompt_templates', 'provider',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('text_generation_jobs', 'error_msg',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('text_generation_jobs', 'result',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('text_generation_jobs', 'finished_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('text_generation_jobs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('text_generation_jobs', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.add_column('poi_info_texts', sa.Column('orphan', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('poi_info_texts', sa.Column('error_msg', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('poi_info_texts', sa.Column('generation_source_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('poi_info_texts_generation_source_id_fkey'), 'poi_info_texts', 'generation_sources', ['generation_source_id'], ['id'])
    op.alter_column('poi_info_texts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('poi_info_texts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('poi_info_texts', 'text_length',
               existing_type=postgresql.ENUM('short', 'medium', 'long', 'very long', name='text_length'),
               nullable=True)
    op.alter_column('poi_info_texts', 'info_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('poi_images', sa.Column('generation_source_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('poi_images_generation_source_id_fkey'), 'poi_images', 'generation_sources', ['generation_source_id'], ['id'])
    op.create_index(op.f('unique_poi_image_variant'), 'poi_images', ['poi_id', 'resolution', 'style_id', 'aspect_id', 'filename'], unique=True)
    op.create_index(op.f('idx_poi_images_task_id'), 'poi_images', ['task_id'], unique=False)
    op.alter_column('poi_images', 'orphan',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('poi_images', 'style_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('poi_images', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('poi_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('poi_images', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', name='enhancement_status'),
               nullable=True,
               existing_server_default=sa.text("'active'::enhancement_status"))
    op.alter_column('poi_images', 'resolution',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='image_resolution'),
               nullable=True)
    op.add_column('poi_audio', sa.Column('generation_source_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('poi_audio_generation_source_id_fkey'), 'poi_audio', 'generation_sources', ['generation_source_id'], ['id'])
    op.create_index(op.f('unique_poi_audio_variant'), 'poi_audio', ['poi_id', 'quality', 'length', 'style_id', 'filename'], unique=True)
    op.create_index(op.f('idx_poi_audio_task_id'), 'poi_audio', ['task_id'], unique=False)
    op.alter_column('poi_audio', 'poi_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('osm_import_log', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('osm_import_log', 'error',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('osm_import_log', 'files',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('osm_import_log', 'regions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('osm_import_log', 'task_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('image_prompt_templates', 'model',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('image_prompt_templates', 'provider',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('image_generation_jobs', 'result',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('image_generation_jobs', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('image_aspects', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('generation_sources', 'model',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('audio_voices', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audio_prompt_templates', 'model',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audio_prompt_templates', 'provider',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audio_generation_jobs', 'result',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audio_generation_jobs', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_table('planet_osm_new_roads',
    sa.Column('osm_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('access', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('addr:housename', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('addr:housenumber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('addr:interpolation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('admin_level', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('aerialway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('aeroway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amenity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('area', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('barrier', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bicycle', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bridge', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('boundary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('building', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('construction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('covered', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('culvert', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cutting', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('denomination', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('disused', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embankment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('foot', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('generator:source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('harbour', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('highway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('historic', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('horse', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('intermittent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('junction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('landuse', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('layer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('leisure', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lock', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('man_made', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('military', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('motorcar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('natural', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('office', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('oneway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('operator', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('place', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('population', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('power', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('power_source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('public_transport', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('railway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ref', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('religion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('route', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('service', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('shop', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sport', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('surface', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('toll', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tourism', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tower:type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tracktype', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tunnel', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('water', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('waterway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wetland', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('width', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wood', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('z_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('way_area', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.HSTORE(text_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('way', sa.NullType(), autoincrement=False, nullable=True)
    )
    op.create_index(op.f('planet_osm_new_roads_way_idx'), 'planet_osm_new_roads', ['way'], unique=False, postgresql_using='gist')
    op.create_index(op.f('planet_osm_new_roads_osm_id_idx'), 'planet_osm_new_roads', ['osm_id'], unique=False)
    op.create_table('osm2pgsql_properties',
    sa.Column('property', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('property', name=op.f('osm2pgsql_properties_pkey'))
    )
    op.create_table('planet_osm_ways_old_20250708200621',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('nodes', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    op.create_table('planet_osm_ways_old_20250712181702',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('nodes', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    op.drop_table('audit_logs')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_oauth_accounts_oauth_name'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_account_id'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    # ### end Alembic commands ###
