"""initial schema

Revision ID: dff171b5ee39
Revises: 
Create Date: 2025-07-29 15:31:06.683967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dff171b5ee39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('planet_osm_new_point_osm_id_idx'), table_name='planet_osm_point')
    op.drop_index(op.f('planet_osm_new_point_way_idx'), table_name='planet_osm_point', postgresql_using='gist')
    op.drop_table('planet_osm_point')
    op.drop_table('audio_generation_jobs')
    op.drop_table('image_prompt_templates')
    op.drop_table('text_generation_jobs')
    op.drop_table('generation_sources')
    op.drop_table('planet_osm_ways_old_20250708200621')
    op.drop_index(op.f('idx_poi_audio_task_id'), table_name='poi_audio')
    op.drop_index(op.f('unique_poi_audio_variant'), table_name='poi_audio')
    op.drop_table('poi_audio')
    op.drop_index(op.f('planet_osm_new_ways_nodes_bucket_idx'), table_name='planet_osm_ways', postgresql_with={'fastupdate': 'off'}, postgresql_using='gin')
    op.drop_table('planet_osm_ways')
    op.drop_table('planet_osm_nodes')
    op.drop_table('spatial_ref_sys')
    op.drop_index(op.f('planet_osm_new_line_osm_id_idx'), table_name='planet_osm_line')
    op.drop_index(op.f('planet_osm_new_line_way_idx'), table_name='planet_osm_line', postgresql_using='gist')
    op.drop_table('planet_osm_line')
    op.drop_index(op.f('planet_osm_new_rels_node_members_idx'), table_name='planet_osm_rels', postgresql_with={'fastupdate': 'off'}, postgresql_using='gin')
    op.drop_index(op.f('planet_osm_new_rels_way_members_idx'), table_name='planet_osm_rels', postgresql_with={'fastupdate': 'off'}, postgresql_using='gin')
    op.drop_table('planet_osm_rels')
    op.drop_table('osm2pgsql_properties')
    op.drop_table('image_styles')
    op.drop_table('audio_voices')
    op.drop_table('text_prompt_templates')
    op.drop_table('audio_prompt_templates')
    op.drop_table('image_generation_jobs')
    op.drop_index(op.f('planet_osm_roads_osm_id_idx'), table_name='planet_osm_roads')
    op.drop_index(op.f('planet_osm_roads_way_idx'), table_name='planet_osm_roads', postgresql_using='gist')
    op.drop_table('planet_osm_roads')
    op.drop_index(op.f('planet_osm_new_polygon_osm_id_idx'), table_name='planet_osm_polygon')
    op.drop_index(op.f('planet_osm_new_polygon_way_idx'), table_name='planet_osm_polygon', postgresql_using='gist')
    op.drop_table('planet_osm_polygon')
    op.drop_table('information_topics')
    op.drop_index(op.f('planet_osm_new_roads_osm_id_idx'), table_name='planet_osm_new_roads')
    op.drop_index(op.f('planet_osm_new_roads_way_idx'), table_name='planet_osm_new_roads', postgresql_using='gist')
    op.drop_table('planet_osm_new_roads')
    op.drop_table('image_aspects')
    op.drop_table('osm_import_log')
    op.drop_index(op.f('idx_poi_images_task_id'), table_name='poi_images')
    op.drop_index(op.f('unique_poi_image_variant'), table_name='poi_images')
    op.drop_table('poi_images')
    op.drop_table('information_styles')
    op.drop_table('planet_osm_ways_old_20250712181702')
    op.drop_table('poi_info_texts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poi_info_texts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('poi_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('info_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('style_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('orphan', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('model', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('prompt_version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('error_msg', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('text_length', postgresql.ENUM('short', 'medium', 'long', 'very long', name='text_length'), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'inactive', name='enhancement_status'), server_default=sa.text("'active'::enhancement_status"), autoincrement=False, nullable=False),
    sa.Column('generation_source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('audio_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['audio_id'], ['poi_audio.id'], name=op.f('poi_info_texts_audio_id_fkey')),
    sa.ForeignKeyConstraint(['generation_source_id'], ['generation_sources.id'], name=op.f('poi_info_texts_generation_source_id_fkey')),
    sa.ForeignKeyConstraint(['style_id'], ['information_styles.id'], name=op.f('poi_info_texts_style_id_fkey')),
    sa.ForeignKeyConstraint(['task_id'], ['text_generation_jobs.task_id'], name=op.f('fk_task_id_text_generation_job')),
    sa.ForeignKeyConstraint(['topic_id'], ['information_topics.id'], name=op.f('poi_info_texts_topic_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('poi_info_texts_pkey'))
    )
    op.create_table('planet_osm_ways_old_20250712181702',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('nodes', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    op.create_table('information_styles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('information_styles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='information_styles_pkey'),
    sa.UniqueConstraint('name', name='information_styles_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('poi_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('poi_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resolution', postgresql.ENUM('low', 'medium', 'high', name='image_resolution'), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'inactive', name='enhancement_status'), server_default=sa.text("'active'::enhancement_status"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('style_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('orphan', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('generation_source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aspect_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint("resolution::text = ANY (ARRAY['low'::character varying::text, 'medium'::character varying::text, 'high'::character varying::text])", name=op.f('poi_images_resolution_check')),
    sa.ForeignKeyConstraint(['aspect_id'], ['image_aspects.id'], name=op.f('poi_images_aspect_id_fkey')),
    sa.ForeignKeyConstraint(['generation_source_id'], ['generation_sources.id'], name=op.f('poi_images_generation_source_id_fkey')),
    sa.ForeignKeyConstraint(['style_id'], ['image_styles.id'], name=op.f('poi_images_style_id_fkey')),
    sa.ForeignKeyConstraint(['task_id'], ['image_generation_jobs.task_id'], name=op.f('poi_images_task_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('poi_images_pkey'))
    )
    op.create_index(op.f('unique_poi_image_variant'), 'poi_images', ['poi_id', 'resolution', 'style_id', 'aspect_id', 'filename'], unique=True)
    op.create_index(op.f('idx_poi_images_task_id'), 'poi_images', ['task_id'], unique=False)
    op.create_table('osm_import_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('regions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('started', 'completed', 'failed', name='osmimportstatus'), server_default=sa.text("'started'::osmimportstatus"), autoincrement=False, nullable=True),
    sa.Column('record_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('osm_import_log_pkey'))
    )
    op.create_table('image_aspects',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('image_aspects_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='image_aspects_pkey'),
    sa.UniqueConstraint('name', name='image_aspects_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('planet_osm_new_roads',
    sa.Column('osm_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('access', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('addr:housename', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('addr:housenumber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('addr:interpolation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('admin_level', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('aerialway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('aeroway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amenity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('area', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('barrier', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bicycle', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bridge', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('boundary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('building', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('construction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('covered', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('culvert', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cutting', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('denomination', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('disused', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embankment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('foot', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('generator:source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('harbour', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('highway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('historic', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('horse', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('intermittent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('junction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('landuse', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('layer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('leisure', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lock', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('man_made', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('military', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('motorcar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('natural', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('office', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('oneway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('operator', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('place', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('population', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('power', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('power_source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('public_transport', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('railway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ref', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('religion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('route', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('service', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('shop', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sport', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('surface', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('toll', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tourism', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tower:type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tracktype', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tunnel', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('water', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('waterway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wetland', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('width', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wood', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('z_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('way_area', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.HSTORE(text_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('way', sa.NullType(), autoincrement=False, nullable=True)
    )
    op.create_index(op.f('planet_osm_new_roads_way_idx'), 'planet_osm_new_roads', ['way'], unique=False, postgresql_using='gist')
    op.create_index(op.f('planet_osm_new_roads_osm_id_idx'), 'planet_osm_new_roads', ['osm_id'], unique=False)
    op.create_table('information_topics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('information_topics_pkey')),
    sa.UniqueConstraint('name', name=op.f('information_topics_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('planet_osm_polygon',
    sa.Column('osm_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('access', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('addr:housename', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('addr:housenumber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('addr:interpolation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('admin_level', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('aerialway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('aeroway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amenity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('area', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('barrier', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bicycle', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bridge', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('boundary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('building', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('construction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('covered', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('culvert', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cutting', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('denomination', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('disused', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embankment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('foot', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('generator:source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('harbour', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('highway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('historic', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('horse', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('intermittent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('junction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('landuse', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('layer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('leisure', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lock', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('man_made', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('military', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('motorcar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('natural', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('office', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('oneway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('operator', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('place', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('population', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('power', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('power_source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('public_transport', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('railway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ref', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('religion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('route', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('service', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('shop', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sport', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('surface', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('toll', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tourism', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tower:type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tracktype', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tunnel', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('water', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('waterway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wetland', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('width', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wood', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('z_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('way_area', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.HSTORE(text_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('way', sa.NullType(), autoincrement=False, nullable=True)
    )
    op.create_index(op.f('planet_osm_new_polygon_way_idx'), 'planet_osm_polygon', ['way'], unique=False, postgresql_using='gist')
    op.create_index(op.f('planet_osm_new_polygon_osm_id_idx'), 'planet_osm_polygon', ['osm_id'], unique=False)
    op.create_table('planet_osm_roads',
    sa.Column('osm_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('access', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('addr:housename', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('addr:housenumber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('addr:interpolation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('admin_level', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('aerialway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('aeroway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amenity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('area', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('barrier', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bicycle', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bridge', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('boundary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('building', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('construction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('covered', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('culvert', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cutting', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('denomination', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('disused', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embankment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('foot', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('generator:source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('harbour', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('highway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('historic', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('horse', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('intermittent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('junction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('landuse', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('layer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('leisure', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lock', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('man_made', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('military', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('motorcar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('natural', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('office', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('oneway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('operator', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('place', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('population', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('power', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('power_source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('public_transport', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('railway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ref', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('religion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('route', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('service', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('shop', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sport', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('surface', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('toll', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tourism', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tower:type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tracktype', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tunnel', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('water', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('waterway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wetland', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('width', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wood', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('z_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('way_area', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.HSTORE(text_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('way', sa.NullType(), autoincrement=False, nullable=True)
    )
    op.create_index(op.f('planet_osm_roads_way_idx'), 'planet_osm_roads', ['way'], unique=False, postgresql_using='gist')
    op.create_index(op.f('planet_osm_roads_osm_id_idx'), 'planet_osm_roads', ['osm_id'], unique=False)
    op.create_table('image_generation_jobs',
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ready', 'generating', 'failed', name='generation_job_status'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_msg', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('task_id', name=op.f('image_generation_jobs_pkey'))
    )
    op.create_table('audio_prompt_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('template', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('voice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['voice_id'], ['audio_voices.id'], name=op.f('fk_voice_audio_voices')),
    sa.PrimaryKeyConstraint('id', name=op.f('audio_prompt_templates_pkey'))
    )
    op.create_table('text_prompt_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('style_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('template', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('text_length', postgresql.ENUM('short', 'medium', 'long', 'very long', name='text_length'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('prompt_templates_pkey')),
    sa.UniqueConstraint('provider', 'model', 'topic_id', 'style_id', 'version', name=op.f('prompt_templates_provider_model_topic_id_style_id_version_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('audio_voices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('audio_voices_pkey')),
    sa.UniqueConstraint('name', name=op.f('audio_voices_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('image_styles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('image_styles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='image_styles_pkey'),
    sa.UniqueConstraint('name', name='image_styles_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('osm2pgsql_properties',
    sa.Column('property', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('property', name=op.f('osm2pgsql_properties_pkey'))
    )
    op.create_table('planet_osm_rels',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('members', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('planet_osm_new_rels_pkey'))
    )
    op.create_index(op.f('planet_osm_new_rels_way_members_idx'), 'planet_osm_rels', [sa.literal_column("planet_osm_new_member_ids(members, 'W'::character(1))")], unique=False, postgresql_with={'fastupdate': 'off'}, postgresql_using='gin')
    op.create_index(op.f('planet_osm_new_rels_node_members_idx'), 'planet_osm_rels', [sa.literal_column("planet_osm_new_member_ids(members, 'N'::character(1))")], unique=False, postgresql_with={'fastupdate': 'off'}, postgresql_using='gin')
    op.create_table('planet_osm_line',
    sa.Column('osm_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('access', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('addr:housename', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('addr:housenumber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('addr:interpolation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('admin_level', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('aerialway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('aeroway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amenity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('area', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('barrier', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bicycle', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bridge', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('boundary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('building', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('construction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('covered', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('culvert', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cutting', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('denomination', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('disused', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embankment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('foot', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('generator:source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('harbour', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('highway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('historic', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('horse', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('intermittent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('junction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('landuse', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('layer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('leisure', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lock', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('man_made', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('military', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('motorcar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('natural', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('office', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('oneway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('operator', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('place', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('population', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('power', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('power_source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('public_transport', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('railway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ref', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('religion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('route', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('service', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('shop', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sport', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('surface', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('toll', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tourism', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tower:type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tracktype', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tunnel', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('water', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('waterway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wetland', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('width', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wood', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('z_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('way_area', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.HSTORE(text_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('way', sa.NullType(), autoincrement=False, nullable=True)
    )
    op.create_index(op.f('planet_osm_new_line_way_idx'), 'planet_osm_line', ['way'], unique=False, postgresql_using='gist')
    op.create_index(op.f('planet_osm_new_line_osm_id_idx'), 'planet_osm_line', ['osm_id'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.create_table('planet_osm_nodes',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('lat', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lon', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('planet_osm_new_nodes_pkey'))
    )
    op.create_table('planet_osm_ways',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('nodes', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('planet_osm_new_ways_pkey'))
    )
    op.create_index(op.f('planet_osm_new_ways_nodes_bucket_idx'), 'planet_osm_ways', [sa.literal_column('planet_osm_new_index_bucket(nodes)')], unique=False, postgresql_with={'fastupdate': 'off'}, postgresql_using='gin')
    op.create_table('poi_audio',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('poi_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('audio_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quality', postgresql.ENUM('low', 'medium', 'high', name='audio_quality'), server_default=sa.text("'medium'::audio_quality"), autoincrement=False, nullable=False),
    sa.Column('length', postgresql.ENUM('short', 'medium', 'long', name='audio_length'), server_default=sa.text("'medium'::audio_length"), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'inactive', name='enhancement_status'), server_default=sa.text("'active'::enhancement_status"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('style_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('orphan', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('generation_source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['generation_source_id'], ['generation_sources.id'], name=op.f('poi_audio_generation_source_id_fkey')),
    sa.ForeignKeyConstraint(['style_id'], ['information_styles.id'], name=op.f('poi_audio_style_id_fkey')),
    sa.ForeignKeyConstraint(['task_id'], ['audio_generation_jobs.task_id'], name=op.f('poi_audio_task_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('poi_audio_pkey'))
    )
    op.create_index(op.f('unique_poi_audio_variant'), 'poi_audio', ['poi_id', 'quality', 'length', 'style_id', 'filename'], unique=True)
    op.create_index(op.f('idx_poi_audio_task_id'), 'poi_audio', ['task_id'], unique=False)
    op.create_table('planet_osm_ways_old_20250708200621',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('nodes', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    op.create_table('generation_sources',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('modality', postgresql.ENUM('text', 'image', 'audio', name='generation_modality'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('generation_sources_pkey'))
    )
    op.create_table('text_generation_jobs',
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ready', 'generating', 'failed', name='generation_job_status'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_msg', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('task_id', name=op.f('text_generation_jobs_pkey'))
    )
    op.create_table('image_prompt_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('style_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aspect_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('template', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['aspect_id'], ['image_aspects.id'], name=op.f('image_prompt_templates_aspect_id_fkey')),
    sa.ForeignKeyConstraint(['style_id'], ['image_styles.id'], name=op.f('image_prompt_templates_style_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('image_prompt_templates_pkey'))
    )
    op.create_table('audio_generation_jobs',
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ready', 'generating', 'failed', name='generation_job_status'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_msg', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('task_id', name=op.f('audio_generation_jobs_pkey'))
    )
    op.create_table('planet_osm_point',
    sa.Column('osm_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('access', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('addr:housename', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('addr:housenumber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('addr:interpolation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('admin_level', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('aerialway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('aeroway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amenity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('area', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('barrier', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bicycle', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bridge', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('boundary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('building', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('capital', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('construction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('covered', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('culvert', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cutting', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('denomination', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('disused', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ele', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embankment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('foot', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('generator:source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('harbour', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('highway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('historic', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('horse', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('intermittent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('junction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('landuse', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('layer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('leisure', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lock', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('man_made', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('military', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('motorcar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('natural', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('office', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('oneway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('operator', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('place', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('population', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('power', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('power_source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('public_transport', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('railway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ref', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('religion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('route', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('service', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('shop', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sport', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('surface', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('toll', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tourism', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tower:type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tunnel', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('water', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('waterway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wetland', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('width', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wood', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('z_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.HSTORE(text_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('way', sa.NullType(), autoincrement=False, nullable=True)
    )
    op.create_index(op.f('planet_osm_new_point_way_idx'), 'planet_osm_point', ['way'], unique=False, postgresql_using='gist')
    op.create_index(op.f('planet_osm_new_point_osm_id_idx'), 'planet_osm_point', ['osm_id'], unique=False)
    # ### end Alembic commands ###
