"""Add task_id  to image generation job

Revision ID: ecd6f82dbe98
Revises: 025e264e0e82
Create Date: 2025-07-31 08:05:35.778527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecd6f82dbe98'
down_revision: Union[str, Sequence[str], None] = '025e264e0e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_generation_jobs', sa.Column('poi_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_generation_jobs', 'poi_id')
    # ### end Alembic commands ###
